version: "3"
services:
  ###  Base de datos PosgreSQL para Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms-inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ###  Base de datos mySQL para Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms-orders
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - 3306:3306
    expose:
      - 3306

  ###  Base de datos PosgreSQL para Products
  db-products:
    container_name: db-products
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms-products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

### Postgres database for KeyCloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db-keycloak
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: 123456789
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
