version: "3"
services:
  ###  Base de datos PosgreSQL para Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms-inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ###  Base de datos mySQL para Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms-orders
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306

  ###  Base de datos PosgreSQL para Products
  db-products:
    container_name: db-products
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms-products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432